version: '3'

services:
  dash-core-regtest:
    image: dash-core-regtest
    container_name: dash-core-regtest
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      -printtoconsole
      -regtest=1
      -whitelist=127.0.0.1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcport=9998
      -rpcuser=dash
      -rpcpassword=password123
      -fallbackfee=0.00001
    ports:
      - "127.0.0.1:9998:9998"
